name: Cross-platform Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Permite ejecución manual desde la UI

jobs:
  build:
    runs-on: ${{ matrix.os }}    # Aquí va en nivel raíz de job
    strategy:
      fail-fast: false            # Que fallen unos jobs no cancela todos
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish for ${{ matrix.rid }}
        run: |
          dotnet publish MistycPawCraftCore.csproj \
            -c Release \
            -r ${{ matrix.rid }} \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -o publish/${{ matrix.rid }}

      - name: Compress build
        run: |
          cd publish/${{ matrix.rid }}
          # En Windows usa powershell para zip, en Linux/macOS zip normal
          if ($Env:OS -eq "Windows_NT") {
            powershell Compress-Archive -Path * -DestinationPath ../../MistycPawCraftCore-${{ matrix.rid }}.zip
          } else {
            zip -r ../../MistycPawCraftCore-${{ matrix.rid }}.zip .
          }
        shell: bash

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: MistycPawCraftCore-${{ matrix.rid }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
