name: Cross-platform Build and Release

on:
  push:
    tags:
      - 'v*'  # Dispara solo con push de un tag como v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - win-x64
          - linux-x64
          - osx-x64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish for ${{ matrix.runtime }}
        run: >
          dotnet publish MistycPawCraftCore.csproj
          -c Release
          -r ${{ matrix.runtime }}
          --self-contained true
          -p:PublishSingleFile=true
          -p:IncludeNativeLibrariesForSelfExtract=true
          -o publish/${{ matrix.runtime }}

      - name: Create zip package
        run: |
          cd publish/${{ matrix.runtime }}
          zip -r ../../MistycPawCraftCore-${{ matrix.runtime }}.zip .
          cd ../..

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: MistycPawCraftCore-${{ matrix.runtime }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
