name: Build and Release MistycPawCraftCore

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish for win-x64
        run: |
          dotnet publish MistycPawCraftCore.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o publish/win-x64

      - name: Compress build
        run: |
          cd publish/win-x64
          powershell Compress-Archive -Path * -DestinationPath ../../MistycPawCraftCore-win-x64.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: MistycPawCraftCore-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
